config/routes.rb
Rails.application.routes.draw do

    root "support_tickets#index"

    resources :support_tickets
    get "/support_tickets/search" => "support_tickets#search"
    post "/support_tickets/search" => "support_tickets#search", as: :search
    get "/support_tickets/search/:page" => "support_tickets#search", as: :page

#             Prefix Verb   URI Pattern                        Controller#Action
#     supporttickets GET    /support_tickets(.:format)          supporttickets#index
#                    POST   /support_tickets(.:format)          supporttickets#create
#  new_supportticket GET    /support_tickets/new(.:format)      supporttickets#new
# edit_supportticket GET    /support_tickets/:id/edit(.:format) supporttickets#edit
#      supportticket GET    /support_tickets/:id(.:format)      supporttickets#show
#                    PATCH  /support_tickets/:id(.:format)      supporttickets#update
#                    PUT    /support_tickets/:id(.:format)      supporttickets#update
#                    DELETE /support_tickets/:id(.:format)      supporttickets#destroy

end

app/models/support_ticket.rb
class SupportTicket < ActiveRecord::Base
    # Validations
    validates :name , presence: true
    VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, format: VALID_EMAIL_REGEX, uniqueness: true
    validates :message, presence: true
    validates :department, presence: true
    # End Validations

    # methods
    scope :search, -> (term) {where("name ILIKE :term OR email ILIKE :term OR department ILIKE :term OR message ILIKE :term", {term: "%#{term}%"})}

    def self.paginate(page)
        order(created_at: :desc).limit(7).offset(7 * (page))
    end


    after_initialize :set_default_values

    def set_default_values
      self.complete ||= false
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/support_tickets_controller.rb
class SupportTicketsController < ApplicationController

    before_action :find_ticket, only: [:show, :edit, :update, :destroy]

    def index
        @tickets = SupportTicket.order(created_at: :desc)
    end

    def new
        @ticket = SupportTicket.new
    end

    def create
        @ticket = SupportTicket.new ticket_params
        if @ticket.save
            redirect_to support_ticket_path(@ticket)
        else
            render :new
        end
    end

    def edit
    end

    def show
    end

    def update
        if @ticket.update ticket_params_update
            redirect_to support_ticket_path(@ticket)
        else
            render :edit
        end
    end

    def search
        page = params[:page].to_i
        @string = params[:search]
        @all_tickets = SupportTicket.search(@string).count
        @tickets = SupportTicket.search(@string)#.paginate(page)
    end

    def destroy
        @ticket.destroy
        redirect_to support_tickets_path
    end

    private

    def ticket_params
        params.require(:support_ticket).permit(:name, :email, :department, :message)
    end
    def ticket_params_update
        params.require(:support_ticket).permit(:name, :email, :department, :message, :complete)
    end

    def find_ticket
        @ticket = SupportTicket.find params[:id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/support_tickets_helper.rb
module SupportTicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Support</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= link_to "Main", root_path %>

<%= yield %>

</body>
</html>

app/views/support_tickets/_edit.html.erb
<div class="form-container">
    <div class="errors">
        <%= @ticket.errors.full_messages.join(", ") %>
    </div>
<%= form_for @ticket do |f| %>
    <div class="input-container">
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: "First and Last Name" %>
    </div>
    <div class="input-container">
        <%= f.label :email %>
        <%= f.text_field :email, {placeholder: "Support Ticket message"}%>
    </div>
    <div class="input-container">
        <%= f.radio_button :department, "sales" %> <span>Sales</span>
        <%= f.radio_button :department, "marketing" %> <span>Marketing </span>
        <%= f.radio_button :department, "technical" %> <span>Technical</span>
    </div>
    <div class="input-container">
        <%= f.label :message %>
        <%= f.text_area :message, {rows: 10, cols: 100, placeholder: "Support ticket message"}%>
    </div>
    <div class="input-container">
        <%= f.radio_button :complete, true %> <span>Done</span>
        <%= f.radio_button :complete, false %> <span>Undone</span>
    </div>
    <%= f.submit "Update" %>
<% end %>
</div>

app/views/support_tickets/_form.html.erb
<div class="form-container">
    <div class="errors">
        <%= @ticket.errors.full_messages.join(", ") %>
    </div>
<%= form_for @ticket do |f| %>
    <div class="input-container">
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: "First and Last Name" %>
    </div>
    <div class="input-container">
        <%= f.label :email %>
        <%= f.text_field :email, {placeholder: "Support Ticket message"}%>
    </div>
    <div class="input-container">
        <%= f.radio_button :department, "sales" %> <span>Sales</span>
        <%= f.radio_button :department, "marketing" %> <span>Marketing </span>
        <%= f.radio_button :department, "technical" %> <span>Technical</span>
    </div>
    <div class="input-container">
        <%= f.label :message %>
        <%= f.text_area :message, {rows: 10, cols: 100, placeholder: "Support ticket message"}%>
    </div>
    <%= f.submit "Create" %>
<% end %>
</div>

app/views/support_tickets/_search.html.erb
<%= form_tag search_path do %>
    <%= text_field_tag :search, "#{@string}" %>
    <%= submit_tag "Search"%>
<% end %>

app/views/support_tickets/edit.html.erb
<%= render "edit" %>
<hr>

app/views/support_tickets/index.html.erb
<h1>Support Tickets</h1>
<div><%= link_to "Create New Ticket", new_support_ticket_path %>
    <%= render "search" %>
</div>

<hr>
<% if @tickets %>
    <% @tickets.each do |ticket| %>
    <div class="ticket-container">

        <%= link_to "Ticket: #{ticket.id}", support_ticket_path(ticket) %>
        <p>
            <%= ticket.name %> | <%= ticket.email %>
        </p>
        <h2><%= ticket.department.capitalize %></h2>
        <% if ticket.message %>
            <div class="message">
                <%= ticket.message.truncate(100) %>
            <div>
        <% end %>
        <p>completed: <% if ticket.complete %>
                        Yes
                        <% else %>
                        No
                    <% end %>
        </p>

        <hr>
    <% end %>
    </div>

<% end %>

app/views/support_tickets/new.html.erb
<%= render "form" %>

app/views/support_tickets/search.html.erb
<%= render "search" %>
<hr>

<!-- <%# (0...@all_tickets/7).each do |page_num| %>
    <%#= link_to page_num + 1, page_path(page_num + 1) %>
<%# end %> -->

<% if @tickets %>
<% @tickets.each do |ticket| %>
<div class="ticket-container">

    <%= link_to "Ticket: #{ticket.id}", support_ticket_path(ticket) %>
    <p>
        <%= ticket.name %> | <%= ticket.email %>
    </p>
    <h2><%= ticket.department.capitalize %></h2>
    <% if ticket.message %>
        <div class="message">
            <%= ticket.message.truncate(100) %>
        <div>
    <% end %>
    <p>completed: <% if ticket.complete %>
                    Yes
                    <% else %>
                    No
                <% end %>
    </p>

    <hr>

<% end %>
<% end %>
<hr>

app/views/support_tickets/show.html.erb
<div class="ticket-container">
    <h1>Ticket: <%= @ticket.id %></h1>
    <h3>Department: <%= @ticket.department.capitalize %></h3>
    <p>
        Name: <%= @ticket.name %> | Email: <%= @ticket.email %>
    </p>
    <p>
        Message: <%= @ticket.message%>
    </p>
    <p>Complete: <% if @ticket.complete %>
                    Yes
                    <% else %>
                    No
                <% end %>
    </p>
    <hr>
    <%= link_to "Edit", edit_support_ticket_path(@ticket) %>
    |
    <%= link_to "Delete", support_ticket_path(@ticket), method: :delete, data: {confirm: "Are you sure?"} %>

</div>